### ISSUE TITLE
Roadmap to 1.0

### ISSUE THREAD

**Issue by theorygeek** [goco-inc/graphql-activerecord#26]
Hey everyone, I wanted to share the plans for this gem. I'm hoping to get to 1.0 within the next few months, which signifies it being really ready for general production use (even though GoCo is using this gem in production right now, as-is).

Here's my current TODO list for this gem:
- [ ] Get a full test suite set up
- [ ] Set up continuous integration
- [ ] Add a demo app
- [ ] Get some better-organized (and easier-to-digest) documentation
- [ ] Try to find a better solution for association-load batching (this is for better cross-compatibility with DBMS's other than PostgreSQL)
- [ ] Try to find a better solution for `model_from_id`, `id_for_model`, and `gid` (maybe)
- [ ] Make model caching more controllable (or just eliminate it) (maybe)
